config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#index'
  #resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :matches]
  resources :sun_signs, only: [:index, :show]
  resources :connections, only: [:index, :new, :show]

  get "welcome", to: "pages#welcome", as: "welcome"
  resources :pages, only: [:welcome]

  #image upload
  post '/upload' => 'users#upload'

  #user edit
  post '/users', to: 'users#create' #create
  get "/users/:id", to: "users#show", as: "user" #show
  get "/users/:id/edit", to: 'users#edit', as: "edit_user"
  patch "/users/:id", to: 'users#update' #update

  delete "/users/:id", to: 'userss#destroy' #destroy

  #session routes
  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  post "sessions", to: "sessions#create", as: "sessions"
  delete "sessions", to: "sessions#destroy"
  get "sessions", to: "sessions#index"

  #connection routes
  post '/connections/:id' => 'connections#create'
  get '/connections/:id' => 'connections#show'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/connection.rb
class Connection < ApplicationRecord
    belongs_to :admirer, :optional => true, class_name: "User"
    belongs_to :sweetheart, :optional => true, class_name: "User"

end

app/models/sun_sign.rb
class SunSign < ApplicationRecord
   has_many :users

end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :sun_sign
    has_many :connections

    has_secure_password
    validates :email, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :password, length: 6..12, :if => :password

    has_one_attached :image
    accepts_nested_attributes_for :connections
    
    has_many :admirers, class_name: 'Connection', foreign_key: :admirer_id
    has_many :sweethearts, class_name: 'Connection', foreign_key: :sweetheart_id


    def users_admired
        self.admirers.where(:admirer_id => self.id).map do |x|
            x.sweetheart
        end
    end 

    def user_sweethearts
        self.sweethearts.where(:sweetheart_id => self.id).map do |x|
            x.admirer 
        end 
    end

    def matches
        self.users_admired & self.user_sweethearts 
    end

    def new_connection(new_sweetheart)
        @start_admirer = self
        @start_sweetheart = User.find_by(id: new_sweetheart.id)
        @connect = Connection.new(admirer_id: @start_admirer.id, sweetheart_id: @start_sweetheart.id, status: "pending")
        @connect.save
    end 

    
   


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # prevent CSRF attacks by raising an exception
    protect_from_forgery with: :exception
    helper_method :logged_in?, :authorized

    # before_action :require_login
    # skip_before_action :require_login, only: [:index, :login, :signup]

    # before_action :authorized
    # skip_before_action :authorized, only: [:new, :create]


    def authorized
        redirect_to login_path unless logged_in?
    end

    def current_user
        @current_user ||= User.find_by(id: session[:email])
    end
      
    def logged_in?
        !current_user.nil?
    end

private
 
  def require_login
    return head(:forbidden) unless session.include? :email
  end


end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController

def index
  @current_user = User.find_by(id: session[:user_id])
        @connections = @current_user.matches
    
end 


def new
  @connection = Connection.new
end

def create
    @current_user = User.find_by(id: session[:user_id])
    @connection = Connection.new
    @connection.admirer_id = @current_user.id
    @connection.sweetheart_id = params[:id]
    @connection.status = "pending"
    @connection.save
    redirect_to user_path(@connection.sweetheart_id)
end 

private

def connection_params 
  params.require(:connection).permit!
end




end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def index
    @user = User.find_by(id: session[:user_id])
end 

def welcome 
    @user = User.find(session[:user_id])
end 

private

def require_login
    return head(:forbidden) unless 
    session.include? :user_id
end 


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


    def index 
        redirect_to root_path
    end


    def new
        
      end
      
      def create
        @user = User.find_by(email: params[:email])
        if @user && @user.authenticate(params[:password])
          session[:user_id] = @user.id
          redirect_to welcome_path
        else
          redirect_to welcome_path #change to a welcome page
        end
      end

      def destroy
        session.delete(:email)
        @current_user = nil
      end

end 

app/controllers/sun_signs_controller.rb
class SunSignsController < ApplicationController

    def index 
        @sun_signs = SunSign.all 
    end 

    def show 
        @sun_sign = SunSign.find(params[:id])
    end 

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController


    def index
        @users = User.all 
    end 

    def show
        @current_user = User.find_by(id: session[:user_id])
        @user = User.find(params[:id])
        @connection = Connection.new
    end 

    def new
        @user = User.new
        @errors = flash[:errors]
    end

    def create 
        @new_user = User.create(user_params)

        if @new_user.valid?
            redirect_to '/login'
        else
            flash[:errors] = @new_user.errors.full_messages
            redirect_to '/signup' 
        end
    end 

    def edit 
        @user = User.find_by(id: session[:user_id])
    end 

    def update 
        @user = User.find_by(id: session[:user_id])
        @user.update_attributes(user_params)
        redirect_to user_path(@user)
    end 

    def destroy
        @user = User.find(params[:id])
        @user.destroy 
        redirect_to users_path
    end 

    def matches
        @users = @current_user.matches
      end

    private

    def user_params 
        params.require(:user).permit!
    end 

    def current_user
        @find = User.find_by(id: session[:user_id])
      end


end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/connections/index.html.erb
<%= link_to "Return To Welcome Page", "/welcome" %>
<h1>Your Connections:</h1>

<hr>
You have <%= @connections.count %> connection(s) in total.<br><br>

<% @connections.each do |c| %>
<%= image_tag c.image, size: "150x150", :style => "float: right" %>
<p><b>Name: </b><%= c.first_name.to_s + " " + c.last_name.to_s %><br>
<b>Birthday: </b> <%= c.dob.strftime("%B %d, %Y") + " (" + c.sun_sign.name + ")" %><br>
<%= link_to "View Full Profile", user_path(c) %> | <%= link_to "Delete Connection", user_path(c) %>

<hr>
<% end %>

app/views/connections/show.html.erb
View Connection Info?

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
      <img alt="Luminate" src="<%= asset_path('luminate.png') %>">
        </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>

      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Luminate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<style>
    body {margin: 5% auto;  color: #444444; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; font-size: 16px; line-height: 1.8; text-shadow: 0 1px 0 #ffffff; max-width: 73%;}
    code {background: white;}
    a {border-bottom: 1px solid #444444; color: #444444; text-decoration: none;}
    a:hover {border-bottom: 0;}
    </style>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<style type="text/css">
html {
      background: url('https://i.ibb.co/p4DVNqq/star.jpg') no-repeat center center fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
}

h1{color: white;letter-spacing:1.3px;}
p{color: white;}
a:link, a:hover{color:white;}
</style>

<h1 style="font-color: #00000">luminate.</h1>
<p>because millenials are really into astrology.</p>

<% if logged_in? %>
    <%= link_to "<button>Welcome back, #{@user}.</button>".html_safe, welcome_path %>
  <%= link_to "Logout", sessions_path, method: :delete %>
  <% else %>
  <%= link_to "<button>Login</button>".html_safe, login_path %> | <%= link_to "<button>Create An Account</button>".html_safe, signup_path, class: "btn btn-primary" %>
  <% end %> 

app/views/pages/welcome.html.erb
<h1>Welcome back, <%= @user.first_name %>!</h1><hr>



Your birthday is <%= @user.dob.strftime("%B %d, %Y") %>, which means your sun is in <%= @user.sun_sign.name + "." %>
There are <%= @user.sun_sign.users.count %> other users with a <%= @user.sun_sign.name  %> sun, but none quite like you. Thank you for being here.
<br><br>
<center><b>Navigate:</B> <%= link_to "View My Profile", user_path(@user) %> 
• <%= link_to "Edit My Profile", edit_user_path(@user) %> • <%= link_to "View My Connections", connections_path %> • <%= link_to "About Sun Sign Astrology", sun_signs_path %> • <%= link_to "Logout", sessions_path, method: :delete, confirm: 'Are you sure?' %></center>

<center><h2><%= link_to "Browse Users With My Sun Sign", sun_sign_path(@user.sun_sign) %></h2></center><hr>
<h2>All Signs:</h2>
<center>• <% SunSign.all.each do |sign| %>
<%= link_to sign.name, sun_sign_path(sign) %> •
<% end %></center><br><br>

<b>About you, <%= @user.sun_sign.name %>:</b> <%= @user.sun_sign.info %>

app/views/sun_signs/index.html.erb
<%= link_to "Return To Welcome Page", "/welcome" %><br>
<h1>About Sun Signs:</h1>
<hr>

<p>Sun sign astrology is the form of astrology most commonly found in many newspaper and magazine columns. It is a simplified system of astrology which considers only the position of the Sun at birth, which is said to be placed within one of the twelve zodiac signs.</p>

<% @sun_signs.each do |sign| %>
<h2><%= sign.name %></h2>
<b>Element:</b> <%= sign.element %><br>
<b>Info:</b> <%= sign.info %>
<% end %>

app/views/sun_signs/show.html.erb
<%= link_to "Return To Welcome Page", "/welcome" %>
<h1><%= @sun_sign.name %> </h1><b>Element:</b> <%= @sun_sign.element %><br><br><hr>


<b>Info:</b> <%= @sun_sign.info %><br><br>

<center><h1>Users With This Sun Sign:</h1></center>
<% @sun_sign.users.each do |user| %>
<div class="entry">
<h2>Name: <%= user.first_name + " " + user.last_name %></h2>
<div align="right"><%= link_to "<button>View Full Profile</button>".html_safe, user_path(user), :style => "width:400px;" %> • <%= link_to "<button>Connect</button>".html_safe, new_connection_path, :style => "width:400px;" %></div>
<%= image_tag user.image, size: "100x100", :style => "float: right; margin: 10px; padding: 5px; border: 3px solid black; align: left" %>
    <p>Date of Birth: <%= user.dob %></p>
        <p>Gender/Pronouns: <%= user.gender + " | " + user.pronouns %></p>
    <p>Orientation: <%= user.orientation.capitalize  %><br><br>
    <div align="center">
    <hr>
    </div>
    <% end %>

app/views/users/edit.html.erb
<div class="edit_user">
<%= link_to "Return To Welcome Page", "/welcome" %>
<h1>Edit Your User Information:</h1>
<hr>
<%= form_for @user do |f| %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
<br>
      <%= f.label :last_name %>
    <%= f.text_field :last_name %><br><br>

<%= f.label :dob, 'Date of Birth' %>:
<%= f.date_select :dob, start_year: 1960, end_year: 2002, order: [:month, :day, :year], prompt: {day: 'Date:', month: 'Month:', year: 'Year:'} %><br>

<%= f.label :sun_sign_id, 'Sun Sign:' %>
<%= f.collection_select :sun_sign_id, SunSign.all, :id, :name, {:prompt => "Select One:"} %> <br>

<%= f.label :gender, 'Gender' %>:
<%= f.select :gender, [['Female', 'female'], ['Male', 'male'], ['Non-Binary', 'non-binary'], ['Other', 'Other']], { :prompt => "Select One:" } %><br>
<%= f.label :pronouns, 'Pronouns' %>:
<%= f.select :pronouns, [['She/Her', 'she/her'], ['He/Him', 'he/him'], ['They/Them', 'they/them'], ['Ze/Zir', 'ze/zir'], ['Xie/Hir', 'xie/hir']], {:prompt => "Select One:"} %><br>
<%= f.label :orientation, 'Orientation' %>:
<%= f.select :orientation, [['Straight', 'straight'], ['Gay', 'gay'], ['Lesbian', 'lesbian'], ['Bisexual', 'bisexual'], ['Asexual', 'asexual'], ['Demisexual', 'demisexual'], ['Pansexual', 'pansexual'], ['Queer', 'queer'], ['Questioning', 'questioning']], {:prompt => "Select One:"} %><br>

<%= f.label :bio, 'Bio' %>:<br>
<%= f.text_area :bio, cols: 20, rows: 8 %><br>

<% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |error| %>
          <li class="error"><%= error %></li>
        <% end %>
      </ul>
    <% end %>

    <%= f.submit "Save" %>
  <% end %>

</div>

app/views/users/index.html.erb
<h1>List of All Users</h1>

<% @users.each do |user| %>
<p><%= user.first_name.to_s + " " + user.last_name.to_s + " | " + user.dob.to_s %></p>
<% end %>

app/views/users/matches.html.erb
<h1>My Matches</h1>

<%= @users.each do |user| %><br>

<%= link_to "View #{user.first_name}", user_path(user) %>

          <%= button_to "Remove", unlike_path(user.id), method: :delete, :class => "btn btn-default", :id => "like_button" %>


  <% end %>

app/views/users/new.html.erb
<h1>sign up for luminate.</h1>
<hr><br>
<div align="center">
<img align="left" src="https://i.ibb.co/5sdccx9/anagodf-nappy.jpg" width="350px">
<%= form_for @user do |f| %>

<% if flash[:errors] %>
     <ul><b> ERROR: please try again!</b>
        <% flash[:errors].each do |error| %>
          <small><li class="error">• <%= error %>.</li></small>
        <% end %>
      </ul>
    <% end %>

<b>LOGIN INFO</b><br>
<%= f.label :email, 'Email Address' %>:
<%= f.text_field :email %><br>
<%= f.label :password %>:
<%= f.password_field :password %><br>
<%= f.label :password_confirmation %>:
<%= f.password_field :password_confirmation %><br><br>

<b>PERSONAL INFO</b><br>
<%= f.label :first_name, 'First Name' %>:
<%= f.text_field :first_name %><br>
<%= f.label :last_name, 'Last Name' %>:
<%= f.text_field :last_name %><br>
<%= f.label :dob, 'Date of Birth' %>:
<%= f.date_select :dob, start_year: 1960, end_year: 2002, order: [:month, :day, :year], prompt: {day: 'Date:', month: 'Month:', year: 'Year:'} %><br>
<br>
<%= f.label :sun_sign_id, 'Sun Sign:' %>
<%= f.collection_select :sun_sign_id, SunSign.all, :id, :name, {:prompt => "Select One:"} %> <br>

<%= f.label :gender, 'Gender' %>:
<%= f.select :gender, [['Female', 'female'], ['Male', 'male'], ['Non-Binary', 'non-binary'], ['Other', 'Other']], { :prompt => "Select One:" } %><br>
<%= f.label :pronouns, 'Pronouns' %>:
<%= f.select :pronouns, [['She/Her', 'she/her'], ['He/Him', 'he/him'], ['They/Them', 'they/them'], ['Ze/Zir', 'ze/zir'], ['Xie/Hir', 'xie/hir']], {:prompt => "Select One:"} %><br>
<%= f.label :orientation, 'Orientation' %>:
<%= f.select :orientation, [['Straight', 'straight'], ['Gay', 'gay'], ['Lesbian', 'lesbian'], ['Bisexual', 'bisexual'], ['Asexual', 'asexual'], ['Demisexual', 'demisexual'], ['Pansexual', 'pansexual'], ['Queer', 'queer'], ['Questioning', 'questioning']], {:prompt => "Select One:"} %><br>

<%= f.label :image, "Upload Profile Picture:" %><br>
<%= f.file_field :image %><br>
<%= f.label :bio, 'Bio' %>:<br>
<%= f.text_area :bio, cols: 20, rows: 8 %><br>

<%= f.submit %>
<% end%>
</div>
<%# <%= button_to "Or Login", login_path, method: "get" %>

app/views/users/show.html.erb
<%= link_to "Return To Welcome Page", "/welcome" %>
<% if @current_user == @user %>
<h1><u>Your Profile:</u><small> <%= @user.first_name + " " + @user.last_name %></small></h1>
<% elsif @current_user != @user %>
<h1><u>User Profile:</u> <small><%= @user.first_name + " " + @user.last_name %></small></h1>
<% end %>


<p><%= image_tag url_for(@user.image), size: "150x150", :style => "float: right" %></p>
<p align="center">

<% if @current_user == @user %>
<%= button_to "Edit Profile", edit_user_path, method: "get" %>
<% elsif @current_user != @user %>
    <% if  @current_user.matches.include?(@user) %>
    You and <%= @user.first_name %> are connected. Disconnect?
    <% else  %>
        You and <%= @user.first_name %> are not yet connected. 
        <center><%= button_to "Connect with #{@user.first_name}", connection_path(@user[:id])  %></center>
    <% end %>
<% end %>

<p><b>Name:</b> <%= @user.first_name + " " + @user.last_name %></p>
<p><b>Date of Birth:</b> <%= @user.dob.to_formatted_s(:long) %></p>
<p><b>Sign:</b> <%= link_to @user.sun_sign.name, sun_sign_path(@user.sun_sign) %> </p>
<p><b>Gender/Pronouns:</b> <%= @user.gender + " | " + @user.pronouns %></p>
<p><b>Orientation:</b> <%= @user.orientation.capitalize  %></p>
<p><b>Bio:</b> <%= @user.bio %></p>